routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/loginPortal', 'Auth\LoginController@loginPortal')->name('loginPortal');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/portal', 'HomeController@portal');

Route::get('/getDatosRut', 'GetController@getDatosRut');
Route::get('/getDiagnostico', 'GetController@getDiagnostico');

Route::resource('/user', 'UserController');
Route::get('/resetPass/{id}', 'UserController@resetPass');
Route::get('/miUser', 'UserController@miUser');

Route::resource('/paciente', 'PacienteController');
Route::get('getProtocolos', 'PacienteController@getProtocolos');
Route::get('getBiopsia', 'PacienteController@getBiopsia');

Route::resource('/comite', 'ComiteController');
Route::get('/pdfComite', 'ComiteController@pdfComite');
Route::get('/clonar', 'ComiteController@clonar');
Route::get('/excelComite', 'ComiteController@excelComite');

Route::resource('/resolucion', 'ResolucionController');

Route::resource('/comiteAdulto', 'ComiteAdultoController');
Route::get('/pdfComiteAdulto', 'ComiteAdultoController@pdfComiteAdulto');
Route::get('/clonarAdulto', 'ComiteAdultoController@clonarAdulto');
Route::get('/excelAdulto', 'ComiteAdultoController@excelAdulto');
Route::get('/estadisticasAdulto', 'ComiteAdultoController@estadisticasAdulto');

Route::resource('/resolucionAdulto', 'ResolucionAdultoController');

Route::resource('/integrantesAdulto', 'IntegrantesAdultoController');
Route::get('/clonarIntegrantesAdulto', 'IntegrantesAdultoController@clonarIntegrantesAdulto');

Route::resource('/comiteInfantil', 'ComiteInfantilController');
Route::get('/pdfComiteInfantil', 'ComiteInfantilController@pdfComiteInfantil');
Route::get('/clonarInfantil', 'ComiteInfantilController@clonarInfantil');
Route::get('/excelInfantil', 'ComiteInfantilController@excelInfantil');

Route::resource('/resolucionInfantil', 'ResolucionInfantilController');

Route::resource('/integrantesInfantil', 'IntegrantesInfantilController');
Route::get('/clonarIntegrantesInfantil', 'IntegrantesInfantilController@clonarIntegrantesInfantil');

Route::get('storage/{archivo}', function ($archivo) {
    $public_path = public_path();
    $url = $public_path.'/storage/'.$archivo;
    if (Storage::exists($archivo))
    {
        return response()->download($url);
    }
    abort(404);
});

app/Comite.php
<?php

namespace App;

use Auth;
use Illuminate\Database\Eloquent\Model;

class Comite extends Model
{
    protected $table = 'com_comite';
    protected $guarded = [];

    public static function boot()
    {
        parent::boot();

        static::creating(function($comite)
        {
            $comite->created_by = Auth::id();
            $comite->id_especialidad = Auth::user()->tx_especialidad;
        });
          
        static::created(function($comite)
        {
            $comite->created_by = Auth::id();
            $comite->id_especialidad = Auth::user()->tx_especialidad;
        });
    }

    public function paciente()
    {
		    return $this->belongsTo('App\Paciente', 'id_paciente');
    }

    public function tipoComite()
    {
		    return $this->belongsTo('App\TipoComite', 'id_tipo_comite');
    }

    public function medico()
    {
	  	  return $this->belongsTo('App\User', 'created_by');
    }

    public function establecimiento()
    {
		    return $this->belongsTo('App\Establecimiento', 'id_hospital_origen');
    }

    public function especialidad()
    {
		    return $this->belongsTo('App\Especialidad', 'id_especialidad');
    }

    public function comorbilidades()
    {
        return $this->belongsToMany('App\Comorbilidad', 'com_comite_comorbilidad', 'id_comite', 'id_comorbilidad');
    }

    public function cie10()
    {
        return $this->belongsTo('App\Cie10', 'id_cie10');
    }

    public function integrantes()
    {
        return $this->belongsToMany('App\User', 'com_comite_integrante', 'id_comite', 'id_medico');
    }

    public function tratamientos()
    {
        return $this->belongsToMany('App\Tratamiento', 'com_comite_tratamiento', 'id_comite', 'id_tratamiento');
    }

    public function formulario()
    {
        switch ($this->id_tipo_comite) {
            case 1:
                return $this->hasOne('App\FormularioRespiratorio', 'id_comite');
                break;
            
            default:
                # code...
                break;
        }
    }

    public function resolucion()
    {
        switch ($this->id_tipo_comite) {
            case 1:
                return $this->hasOne('App\ResolucionRespiratorio', 'id_comite');
                break;
            
            default:
                # code...
                break;
        }
    }
}

app/Http/Controllers/ComiteController.php
<?php

namespace App\Http\Controllers;

use App\Comite;
use App\User;
use App\Paciente;
use App\TipoComite;
use App\Establecimiento;
use App\Especialidad;
use App\Comorbilidad;
use App\Cie10;
use App\FormularioRespiratorio;
use Illuminate\Http\Request;
use App\Exports\ComiteExport;
use Maatwebsite\Excel\Facades\Excel;

class ComiteController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $comites = Comite::with('paciente')
            ->when($request->has('medicos') && !is_null($request->medicos), function ($collection) use ($request){
                $collection->whereIn('created_by', $request->medicos);
            })
            ->when($request->has('especialidades') && !is_null($request->especialidades), function ($collection) use ($request){
                $collection->whereIn('id_especialidad', $request->especialidades);
            })
            ->when($request->has('fc_inicio') && !is_null($request->fc_inicio), function ($collection) use ($request){
                return $collection->where('fc_presentacion', '>=', date("Y-m-d 00:00:00", strtotime($request->fc_inicio)))
                        ->where('fc_presentacion', '<=', date("Y-m-d 00:00:00", strtotime($request->fc_termino)));
            })
            ->when($request->resuelto == 0, function ($collection) use ($request){
                $collection->whereIn('bo_resuelto', [0, 73]);
            })
            ->when($request->resuelto == 1, function ($collection) use ($request){
                $collection->where('bo_resuelto', 72);
            })
            ->orderBy('id', 'DESC')
            ->paginate(10);

        $tipoComite = TipoComite::find($request->tipo_comite);
        $especialidades = Especialidad::get();
        $medicos = User::get();
        session(['url' => url()->full()]);
        return view('comite.index', compact('tipoComite', 'comites', 'especialidades', 'medicos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $tipoComite = TipoComite::find($request->tipo_comite);
        $establecimientos = Establecimiento::get();
        $comorbilidades = Comorbilidad::get();
        return view('comite.register', compact('tipoComite', 'establecimientos', 'comorbilidades'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pacienteRequest = [
            'nr_ficha' => $request->nr_ficha,
            'tx_apellido_paterno' => $request->tx_apellido_paterno,
            'tx_apellido_materno' => $request->tx_apellido_materno,
            'tx_nombre' => $request->tx_nombre,
            'fc_nacimiento' => $request->fc_nacimiento,
            'tx_telefono' => $request->tx_telefono,
            'tx_mail' => $request->tx_mail,
            'id_sexo' => $request->id_sexo,
            'id_prevision' => $request->id_prevision,
            'id_clasificacion_fonasa' => $request->id_clasificacion_fonasa,
        ];
        $rutDV = explode("-",$request->tx_rut);
        $paciente = Paciente::updateOrCreate([
            'nr_run' => $rutDV[0],
            'tx_digito_verificador' => $rutDV[1],
            'id_tipo_dentificacion_paciente' => 1,
        ], $pacienteRequest);
        
        $comiteRequest = [
            'fc_presentacion' => $request->fc_presentacion,
            'id_paciente' => $paciente->id,
            'id_tipo_comite' => $request->id_tipo_comite,
            'id_hospital_origen' => $request->id_hospital_origen,
            'id_cie10' => $request->id_cie10,
        ];
        if(isset($request->archivo)){
            $tx_archivo = $request->file('archivo')->store('public');
            $tx_archivo = substr($tx_archivo, 7);
            $comiteRequest['tx_archivo'] = $tx_archivo;
        }
        if($request->bo_clonar){
            $comite = Comite::create($comiteRequest);
        }else{
            $comite = Comite::updateOrCreate([
                'id' => $request->id,
            ], $comiteRequest);
        }

        $formularioRequest = $request->except('_token', 'id', 'id_sexo', 'id_prevision', 'id_clasificacion_fonasa', 'id_tipo_comite', 'bo_clonar', 'id_hospital_origen', 'fc_presentacion', 'tx_rut', 'tx_nombre', 'tx_apellido_paterno', 'tx_apellido_materno', 'fc_nacimiento', 'tx_mail', 'tx_telefono', 'nr_ficha', 'tx_paciente_nuevo', 'comorbilidades', 'archivo', 'id_cie10');
        switch ($request->id_tipo_comite) {
            case 1:
                $formulario = FormularioRespiratorio::updateOrCreate([
                    'id_comite' => $comite->id,
                ], $formularioRequest);
                break;
            case 2:
                # code...
                break;
            default:
                # code...
                break;
        }
        $comite->comorbilidades()->sync($request->comorbilidades);
        if($comite){
            return redirect('/comite?resuelto=0&tipo_comite='.$request->id_tipo_comite)->with('message', "Se ha guardado exitosamente");
        }else{
            return redirect('/comite?resuelto=0&tipo_comite='.$request->id_tipo_comite)->with('error', "No se ha guardado");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Comite  $comite
     * @return \Illuminate\Http\Response
     */
    public function show(Comite $comite)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Comite  $comite
     * @return \Illuminate\Http\Response
     */
    public function edit(Comite $comite)
    {
        $comite = Comite::with('comorbilidades', 'cie10')->find($comite->id);
        $formulario = $comite->formulario;
        $tipoComite = TipoComite::find($comite->id_tipo_comite);
        $establecimientos = Establecimiento::get();
        $comorbilidades = Comorbilidad::get();
        return view('comite.register', compact('comite', 'formulario', 'tipoComite', 'establecimientos', 'comorbilidades'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Comite  $comite
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comite $comite)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comite  $comite
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comite $comite)
    {
        //
    }

    public function pdfComite(Request $request)
    {
        $comite = Comite::with('paciente')->find($request->id);
     
        $pdf = \PDF::loadView('comite.pdf', compact('comite'));
     
        return $pdf->stream('archivo.pdf');
    }

    public function clonar(Request $request)
    {
        $comite = Comite::with('comorbilidades', 'cie10')->find($request->id);
        $tipoComite = TipoComite::find($comite->id_tipo_comite);
        $formulario = $comite->formulario;
        $establecimientos = Establecimiento::get();
        $comorbilidades = Comorbilidad::get();
        $bo_clonar = 1;
        return view('comite.register', compact('comite', 'tipoComite', 'formulario', 'establecimientos', 'comorbilidades', 'bo_clonar'));
    }

    public function excelComite(Request $request)
    {
        $comites = Comite::with('paciente')
            ->when($request->has('medicos') && !is_null($request->medicos), function ($collection) use ($request){
                $collection->whereIn('created_by', $request->medicos);
            })
            ->when($request->has('especialidades') && !is_null($request->especialidades), function ($collection) use ($request){
                $collection->whereIn('id_especialidad', $request->especialidades);
            })
            ->when($request->has('fc_inicio') && !is_null($request->fc_inicio), function ($collection) use ($request){
                return $collection->where('fc_presentacion', '>=', date("Y-m-d 00:00:00", strtotime($request->fc_inicio)))
                        ->where('fc_presentacion', '<=', date("Y-m-d 00:00:00", strtotime($request->fc_termino)));
            })
            ->when($request->resuelto == 0, function ($collection) use ($request){
                $collection->whereIn('bo_resuelto', [0, 73]);
            })
            ->when($request->resuelto == 1, function ($collection) use ($request){
                $collection->where('bo_resuelto', 72);
            })
            ->orderBy('id', 'DESC')
            ->get();
        return Excel::download(new ComiteExport($comites), 'comiteRespiratorio'.$request->fc_inicio.'&'.$request->fc_termino.'.xlsx');
    }
}

resources/views/comite/adulto/excel.blade.php
<table>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Rut</th>
        <th>Edad</th>
        <th>F. Nacimiento</th>
        <th>Sexo</th>
        <th>Paciente Nuevo</th>
        <th>F. Presentación</th>
        <th>Médico</th>
        <th>Especialidad</th>
        <th>Diagnóstico</th>
        <th>Tratamiento comite</th>
        <th>Tratamiento propuesto</th>
        <th>Plan</th>
        <th>Curativo</th>
        <th>CIEO</th>
        <th>Cateter QT</th>
    </tr>
    @foreach($comites as $comite)
    <tr>
        <td>{{$comite->id}}</td>
        <td>{{$comite->tx_nombre_completo}}</td>
        <td>{{$comite->tx_rut}}</td>
        <td>{{$comite->edad}}</td>
        <td>@if((isset($comite->fc_nacimiento) && $comite->fc_nacimiento != '0000-00-00'))
            {{date('d/m/Y', strtotime(str_replace("/",".",$comite->fc_nacimiento)))}}
        @else 
            Sin Información
        @endif</td>
        <td>@if($comite->id_sexo == 1)
                Hombre
            @elseif($comite->id_sexo == 2)
                Mujer
            @endif
        </td>
        <td>{{$comite->tx_paciente_nuevo}}</td>
        <td>{{date('d-m-Y', strtotime($comite->fc_ingreso))}}</td>
        <td>{{$comite->tx_medico}}</td>
        <td>{{ucwords(mb_strtolower($comite->tx_especialidad))}}</td>
        <td>{{$comite->tx_diagnostico_actual}}</td>
        <td>{{isset($comite->resolucion->tx_tratamiento_comite) ? $comite->resolucion->tx_tratamiento_comite : ''}}</td>
        <td>{{isset($comite->resolucion->tx_tratamiento_propuesto) ? $comite->resolucion->tx_tratamiento_propuesto : ''}}</td>
        <td>{{isset($comite->tx_plan) ? $comite->tx_plan : ''}}</td>
        <td>{{isset($comite->resolucion->tx_curativo) ? $comite->resolucion->tx_curativo : ''}}</td>
        <td>{{isset($comite->tx_Cie10) ? $comite->tx_Cie10 : ''}}</td>
        <td>{{$comite->resolucion->tx_cateter_qt ?? ''}}</td>
    </tr>
    @endforeach
</table>

resources/views/comite/adulto/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Pacientes Adultos')

@section('content_header')
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-danger">
            <i class="fa fa-exclamation-triangle"></i> {{ session()->get('error') }}
        </div>
    @endif
@stop

@section('content')
		{{-- <form class="form-horizontal" id="form" method="POST">
			{{ csrf_field() }} --}}
	<div class="card card-info">
		<div class="card-header">
		<h3 class="card-title">Lista de Pacientes Adulto {{request()->resuelto == 1 ? 'Resueltos' : 'Por Resolver'}}</h3>
		</div>
		<!-- /.card-header -->
		<!-- form start -->
		<div class="card-body">
            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-horizontal">
                            <input type="hidden" id="resuelto" name="resuelto" value="{{request()->resuelto}}"/>
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <label for="fc_inicio">Fecha de Inicio</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                        </div>
                                        <input type="date" class="form-control" id="fc_inicio" name="fc_inicio" value="{{isset(request()->fc_inicio) ? request()->fc_inicio : date("Y-m-d")}}">
                                    </div>	
                                </div>
                                <div class="col-sm-4">
                                    <label for="fc_termino">Fecha de Termino</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                        </div>
                                        <input type="date" class="form-control" id="fc_termino" name="fc_termino" value="{{isset(request()->fc_termino) ? request()->fc_termino : date("Y-m-d")}}">
                                    </div>	
                                </div>
                                <div class="col-sm-4 text-right">
                                    <a href="comiteAdulto?resuelto={{request()->resuelto == 1 ? '0' : '1'}}" class="{{request()->resuelto == 1 ? 'btn btn-warning' : 'btn btn-success'}}">{{request()->resuelto == 1 ? 'Por Resolver' : 'Resuelto'}}</a>
                                    <button type="submit" class="btn btn-info">Filtrar</button>
                                    <button type="submit" onclick="excel()" class="btn btn-success"><i class="fa fa-file-excel" style="color:white"></i></button>
                                    <a href="comiteAdulto/create" title="Nuevo Comite" class="btn btn-success"><i class="fa fa-plus" style="color:white"></i></a>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <label for="especialidades">Especialidad:</label>
                                    <select class="select2 select2-hidden-accessible" id="especialidades" name="especialidades[]" multiple="" data-placeholder="Seleccione especialidad(es)" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true">
                                        @foreach ($especialidades as $especialidad)
                                            <option value={{$especialidad->id}} >{{$especialidad->tx_nombre_minuscula}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-sm-4">
                                    <label for="medicos">Medico:</label>
                                    <select class="select2 select2-hidden-accessible" id="medicos" name="medicos[]" multiple="" data-placeholder="Seleccione medico(s)" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true">
                                        @foreach ($medicos as $medico)
                                            <option value={{$medico->id}} >{{$medico->tx_nombre_minuscula}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </form>
                        <table class="table table-striped table-hover" id="tableUsers">
                            <thead>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Rut</th>
                                <th>F. Presentación</th>
                                @if (request()->resuelto == 1)
                                    <th>F. Resolución</th>
                                @endif
                                <th>Médico</th>
                                <th>Especialidad</th>
                                {{-- <th>Estado</th> --}}
                                @if (request()->adulto == 1 && request()->resuelto == 0)
                                    <th>Rev. Imagen</th>
                                    <th>Cateter QT</th>
                                @endif
                                <th><i class="fa fa-cog"></i></th>
                            </thead>
                            <tbody>
                                @foreach ($comites as $comite)
                                    <tr role="row" class="odd">
                                        <td>{{$comite->id}}</td>
                                        <td><a href="paciente/1?rut={{$comite->tx_rut}}">{{$comite->tx_nombre_completo}}<a></td>
                                        <td>{{$comite->tx_rut}}</td>
                                        <td>{{date('d-m-Y', strtotime($comite->fc_ingreso))}}</td>
                                        @if (request()->resuelto == 1)
                                            <td>{{isset($comite->resolucion) ? date('d-m-Y', strtotime($comite->resolucion->fc_resolucion)) : ''}}</td>
                                        @endif
                                        <td>{{$comite->tx_medico}}</td>
                                        <td>{{ucwords(mb_strtolower($comite->tx_especialidad))}}</td>
                                        {{-- <td>{{isset($comite->resolucion) ? isset($comite->resolucion->estado) ? $comite->resolucion->estado->tx_nombre_minuscula : $comite->resolucion->tx_estado : 'Indefinido'}}</td> --}}
                                        @if (request()->adulto == 1 && request()->resuelto == 0)
                                            <td>{{isset($comite->bo_revisar_imagen) && $comite->bo_revisar_imagen == 1 ? 'Si' : 'No'}}</td>
                                            <td>{{isset($comite->resolucion) ? $comite->resolucion->tx_cateter_qt : ''}}</td>
                                        @endif
                                        <td>
                                            <form action="{{ route('comiteAdulto.destroy',$comite->id) }}" method="POST">
                                                <div class="btn-group">
                                                    @if (request()->resuelto == 0)
                                                        @if (isset($comite->resolucion))
                                                            <a class="btn btn-success btn-xs" href="resolucionAdulto/create?id={{$comite->id}}" title="Resolver"><i class="fa fa-check" style="color:white"></i></a>
                                                            {{-- <a class="btn btn-success btn-xs" href="resolucion/{{$comite->id}}/edit?adulto={{request()->adulto}}" title="Resolver (editar)"><i class="fa fa-check" style="color:white"></i></a> --}}
                                                        @else
                                                            <a class="btn btn-success btn-xs" href="resolucionAdulto/create?id={{$comite->id}}" title="Resolver"><i class="fa fa-check" style="color:white"></i></a>
                                                        @endif
                                                        <a class="btn btn-warning btn-xs" href="comiteAdulto/{{$comite->id}}/edit" title="Editar"><i class="fa fa-edit" style="color:white"></i></a>
                                                    @endif
                                                    <a class="btn btn-secondary btn-xs" href="pdfComiteAdulto?resuelto={{request()->resuelto}}&id={{$comite->id}}" title="Ver Comite" target="_blank"><i class="fa fa-file-pdf" style="color:white"></i></a>
                                                    @if (isset($comite->tx_archivo) && $comite->tx_archivo != '')
                                                        <a class="btn btn-primary btn-xs" href="http://10.4.237.11/comite_oncologico/_lib/file/doc/{{$comite->tx_archivo}}" title="Archivo" target="_blank"><i class="fa fa-file" style="color:white"></i></a>
                                                    @endif
                                                    <a class="btn btn-info btn-xs" href="clonarAdulto?id={{$comite->id}}" title="Clonar Comite"><i class="fa fa-copy" style="color:white"></i></a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button onclick="return confirm('¿Esta seguro de eliminar a este Comite?');" type="submit" class="btn btn-danger btn-xs" title="Eliminar Comite"><i class="fa fa-trash" style="color:white"></i></button>
                                                </div>
                                            </form>
										</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $comites->appends(request()->query())->links() }}
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@stop

@section('js')
<script>
    function excel(){
        var url = "excelAdulto?"+$( "form" ).serialize();
        window.location.href = url;
        alert('descargando excel...');
    }

    @if(isset(request()->especialidades))
        var user = @json(request()->all());
        var especialidades = user.especialidades;
        $("#especialidades").val(especialidades).trigger('change');
    @endif

    @if(isset(request()->medicos))
        var user = @json(request()->all());
        var medicos = user.medicos;
        $("#medicos").val(medicos).trigger('change');
    @endif

	$(".alert-success").fadeTo(20000, 500).slideUp(500, function(){
        $(".alert-success").slideUp(1000);
    });

    $(".alert-danger").fadeTo(20000, 5000).slideUp(500, function(){
        $(".alert-danger").slideUp(1000);
    });

    $('.select2').select2();
</script>
@stop