routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/loginPortal', 'Auth\LoginController@loginPortal')->name('loginPortal');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/portal', 'HomeController@portal');

Route::get('/getDatosRut', 'GetController@getDatosRut');
Route::get('/getDiagnostico', 'GetController@getDiagnostico');

Route::resource('/user', 'UserController');
Route::get('/resetPass/{id}', 'UserController@resetPass');
Route::get('/miUser', 'UserController@miUser');

Route::resource('/paciente', 'PacienteController');
Route::get('getProtocolos', 'PacienteController@getProtocolos');
Route::get('getBiopsia', 'PacienteController@getBiopsia');

Route::resource('/comite', 'ComiteController');
Route::get('/pdfComite', 'ComiteController@pdfComite');
Route::get('/clonar', 'ComiteController@clonar');
Route::get('/excelComite', 'ComiteController@excelComite');

Route::resource('/resolucion', 'ResolucionController');

Route::resource('/comiteAdulto', 'ComiteAdultoController');
Route::get('/pdfComiteAdulto', 'ComiteAdultoController@pdfComiteAdulto');
Route::get('/clonarAdulto', 'ComiteAdultoController@clonarAdulto');
Route::get('/excelAdulto', 'ComiteAdultoController@excelAdulto');
Route::get('/estadisticasAdulto', 'ComiteAdultoController@estadisticasAdulto');

Route::resource('/resolucionAdulto', 'ResolucionAdultoController');

Route::resource('/integrantesAdulto', 'IntegrantesAdultoController');
Route::get('/clonarIntegrantesAdulto', 'IntegrantesAdultoController@clonarIntegrantesAdulto');

Route::resource('/comiteInfantil', 'ComiteInfantilController');
Route::get('/pdfComiteInfantil', 'ComiteInfantilController@pdfComiteInfantil');
Route::get('/clonarInfantil', 'ComiteInfantilController@clonarInfantil');
Route::get('/excelInfantil', 'ComiteInfantilController@excelInfantil');

Route::resource('/resolucionInfantil', 'ResolucionInfantilController');

Route::resource('/integrantesInfantil', 'IntegrantesInfantilController');
Route::get('/clonarIntegrantesInfantil', 'IntegrantesInfantilController@clonarIntegrantesInfantil');

Route::get('storage/{archivo}', function ($archivo) {
    $public_path = public_path();
    $url = $public_path.'/storage/'.$archivo;
    if (Storage::exists($archivo))
    {
        return response()->download($url);
    }
    abort(404);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'sec_users';
    protected $guarded = [];
    public $timestamps = false;

    public static function boot()
    {
        parent::boot();

        static::creating(function($user)
        {
            $password = substr($user->login, 0, 4);
            $user->password = $password;
            $user->pswd = $password;
        });
          
        static::created(function($user)
        {
            $password = substr($user->login, 0, 4);
            $user->password = $password;
            $user->pswd = $password;
        });
    }

    public function setPswdAttribute($value){
        $this->attributes['pswd'] = sha1(intval($value));
    }

    public function setPasswordAttribute($value){
        $this->attributes['password'] = bcrypt(intval($value));
    }

    protected $appends = ['tx_nombre_minuscula', 'tx_rut'];

    public function getTxNombreMinusculaAttribute()
    {
        return ucwords(mb_strtolower("{$this->name}"));
    }

    public function getTxRutAttribute()
    {
        return "{$this->login}";
    }

    public function especialidad()
    {
		return $this->belongsTo('App\Parametros', 'tx_especialidad');
    }

    public function establecimiento()
    {
		return $this->belongsTo('App\Parametros', 'tx_establecimiento');
    }

    public function grupo()
    {
		return $this->belongsTo('App\UserGrupo', 'login', 'login');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\User;
use App\UserPortal;
use App\UserGrupo;
use App\Parametros;
use App\Grupo;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(User::class, 'user');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tx_rut = str_replace(".","",request()->tx_rut);
        $users = User::with('especialidad', 'establecimiento')
                ->when($request->has('tx_rut') && !is_null($request->tx_rut), function ($collection) use ($request, $tx_rut) {
                    return $collection->whereRaw("login LIKE ?", ['%'.$tx_rut.'%']);
                })
                ->when($request->has('tx_nombre') && !is_null($request->tx_nombre), function ($collection) use ($request) {
                    return $collection->whereRaw("name LIKE ?", ['%'.$request->tx_nombre.'%']);
                })
                ->orderBy('id')
                ->paginate(10);
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('admin', User::class);
        $especialidades = Parametros::where('tx_tipo', 'Especialidad')->get();
        $establecimientos = Parametros::where('tx_tipo', 'Establecimiento')->get();
        $grupos = Grupo::get();
        return view('user.register', compact('especialidades', 'establecimientos', 'grupos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $userPortal = UserPortal::with('sistemas')->where('rut', $request->login)->first();
        if(isset($userPortal)){
            $userPortal->sistemas()->attach(2);
        }else{
            $userRequest = [
                'rut' => $request->login,
                'nombre' => $request->name,
            ];
            $userPortal = UserPortal::create($userRequest);
            $userPortal->sistemas()->sync([2]);
        }
        if (!isset($request->active)) {
            $request->request->add(['active' => 'N']);
        }
        $user = User::updateOrCreate(['login'=> $request->login], $request->except('_token', 'miUser', 'group_id'));
        if (!isset($request->miUser)) {
            $userGrupo = UserGrupo::updateOrCreate([
                'login'=> $request->login
            ],[
                'login'=> $request->login,
                'group_id'=> $request->group_id
            ]);        
        }
        if (!$user) {
            return redirect()->back()->with('error', 'Error al guardar');
        }
        if (!isset($request->miUser)){
            return redirect('/user')->with('message', 'El usuario '.$user->name.' a sido guardado exitosamente');
        }
        return redirect('/home')->with('message', 'El usuario '.$user->name.' a sido guardado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // $user = User::with('especialidad', 'establecimiento', 'grupo')->find($user->id);
        $especialidades = Parametros::where('tx_tipo', 'Especialidad')->get();
        $establecimientos = Parametros::where('tx_tipo', 'Establecimiento')->get();
        $grupos = Grupo::get();
        return view('user.register', compact('user', 'especialidades', 'establecimientos', 'grupos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->grupo()->delete();
        if($user->forceDelete()){
            return redirect('/user')->with('message', "El usuario a sido eliminado correctamente");
        }else{
            return redirect('/user')->with('error', "El usuario no a sido eliminado, intente nuevamente");
        }
    }

    public function resetPass($id) // Reiniciar Contraseña
    {
        $user = User::find($id);

        // PARA REINICIAR TODAS LAS CONTRASEÑAS BCRYPT (AGREGAR password A LA TABLA cb_usuario)
        // $users = User::get();
        // foreach ($users as $key => $user) {
        //     $password = substr($user->login, 0, 4);
        //     $user->password = $password;
        //     $user->save();
        // }

        $password = substr($user->login, 0, 4);
        $user->password = $password;
        $user->save();

        return redirect('/user')->with('message', "La contraseña del usuario ".$user->name."  a sido reiniciada");
    }

    public function miUser() // Modificar mi usuario
    {
        $user = User::find(Auth::user()->id);
        $especialidades = Parametros::where('tx_tipo', 'Especialidad')->get();
        $establecimientos = Parametros::where('tx_tipo', 'Establecimiento')->get();
        $grupos = Grupo::get();
        $miUser = true;
        return view('user.register', compact('user', 'especialidades', 'establecimientos', 'grupos', 'miUser'));
    }
}

resources/views/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Lista de Usuarios')

@section('content_header')
    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-danger">
            <i class="fa fa-exclamation-triangle"></i> {{ session()->get('error') }}
        </div>
    @endif
@stop

@section('content')
		{{-- <form class="form-horizontal" id="form" method="POST">
			{{ csrf_field() }} --}}
			

	<div class="card card-info">
		<div class="card-header">
		<h3 class="card-title">Lista de Usuarios</h3>
		</div>
		<!-- /.card-header -->
		<!-- form start -->
		<div class="card-body">
            <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-horizontal">
                            <div class="form-group row">
                                <div class="col-sm-5">
                                    <input type="text" name="tx_nombre" class="form-control" id="tx_nombre" placeholder="Nombre" value="{{request()->tx_nombre}}">
                                </div>
                                <div class="col-sm-3">
                                    <input type="text" name="tx_rut" class="form-control" id="tx_rut" placeholder="Rut" value="{{request()->tx_rut}}">
                                </div>
                                <div class="col-sm-4 text-right">
                                    <button type="submit" class="btn btn-info">Filtrar</button>
                                    <a href="user/create" class="btn btn-success" type="button" title="Agregar Usuario"><i class="fa fa-user-plus" style="color:white"></i></a>
                                </div>
                            </div>
                        </form>
                        <table class="table table-striped table-hover" id="tableUsers">
                            <thead>
                                <th>ID</th>
                                <th>Nombre</th>
                                <th>Rut</th>
                                <th>Especialidad</th>
                                <th>Establecimiento</th>
                                <th>Tipo Profesional</th>
                                <th>Activo</th>
                                <th><i class="fa fa-cog"></i></th>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr role="row" class="odd">
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->tx_nombre_minuscula}}</td>
                                        <td>{{$user->tx_rut}}</td>
                                        <td>{{$user->especialidad->tx_nombre_minuscula}}</td>
                                        <td>{{$user->establecimiento->tx_nombre_minuscula}}</td>
                                        <td>{{$user->tx_tipo_profesional}}</td>
                                        <td>{{$user->active == 'Y' ? 'Si' : 'No'}}</td>
										<td>
                                            <form action="{{ route('user.destroy',$user->id) }}" method="POST">
                                                <div class="btn-group">
                                                <a class="btn btn-warning btn-xs" href="{{ route('user.edit',$user->id) }}" title="Editar Usuario"><i class="fa fa-edit" style="color:white"></i></a>
                                                <a class="btn btn-primary btn-xs" onclick="return confirm('¿Esta seguro de reiniciar la contraseña de {{$user->tx_nombre_minuscula}}?');" href="resetPass/{{$user->id}}" title="Reiniciar Contraseña"><i class="fa fa-lock-open" style="color:white"></i></a>
                                                @csrf
                                                @method('DELETE')
                                                <button onclick="return confirm('¿Esta seguro de eliminar a {{$user->tx_nombre_minuscula}}?');" type="submit" class="btn btn-danger btn-xs" title="Eliminar Usuario"><i class="fa fa-trash" style="color:white"></i></button>
                                                </div>
                                            </form>
										</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{ $users->appends(request()->query())->links() }}
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
@stop

@section('js')
<script>
	$(".alert-success").fadeTo(20000, 500).slideUp(500, function(){
        $(".alert-success").slideUp(1000);
    });

    $(".alert-danger").fadeTo(20000, 5000).slideUp(500, function(){
        $(".alert-danger").slideUp(1000);
    });
</script>
@stop

resources/views/user/register.blade.php
@extends('adminlte::page')

@section('title', 'Registro Usuario')

@section('content')
		{{-- <form class="form-horizontal" id="form" method="POST">
			{{ csrf_field() }} --}}
			

	<div class="card card-info">
		<div class="card-header">
		<h3 class="card-title">{{ isset($user) ? 'Editar cuenta' : 'Crear cuenta'}}</h3>
		</div>
		<!-- /.card-header -->
		<!-- form start -->
		<form role="form" class="form-horizontal" id="form" method="POST" action="{{action('UserController@store')}}">
			{{ csrf_field() }}
			<input type="hidden" id="miUser" name="miUser" value="{{isset($miUser) ? $miUser : ''}}"/>
			<div class="card-body">
				<div class="form-group">
					<div class="row">
						<div class="col-sm-3">
							<label for="login">Rut:<span style="color:#FF0000";>*</span></label>
							<input class="form-control" id="login" name="login" value="{{isset($user) ? $user->login : ''}}" {{isset($user) ? 'readonly' : ''}} onblur="getPerson($(this).val());" required>
						</div>
						<div class="col-sm-3">
							<label for="name">Nombre:<span style="color:#FF0000";>*</span></label>
							<input class="form-control" id="name" name="name" value="{{isset($user) ? $user->name : ''}}" required>
						</div>
						<div class="col-sm-3">
							<label for="email">Email:</label>
							<input type="email" class="form-control" id="email" name="email" value="{{isset($user) ? $user->email : ''}}">
						</div>
						@if(!isset($miUser))
							<div class="col-sm-3">
								<div class="custom-control custom-checkbox">
									<input class="custom-control-input" type="checkbox" id="active" name="active" value="Y" checked>
									<label for="active" class="custom-control-label">Activo</label>
								</div>
							</div>
						@endif
					</div>
				</div>
				@if(!isset($miUser))
					<div class="form-group">
						<div class="row">
							<div class="col-sm-3">
								<label for="tx_especialidad">Especialidad:<span style="color:#FF0000";>*</span></label>
								<select class="select2 select2-hidden-accessible" id="tx_especialidad" name="tx_especialidad" data-placeholder="Seleccione especialidad" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" required>
									<option value=""></option>
									@foreach ($especialidades as $especialidad)
										<option value={{$especialidad->id}} {{isset($user->especialidad) && $user->especialidad->id == $especialidad->id ? "selected" : ""}}>{{$especialidad->tx_nombre_minuscula}}</option>
									@endforeach
								</select>
							</div>
							<div class="col-sm-3">
								<label for="tx_establecimiento">Establecimiento:<span style="color:#FF0000";>*</span></label>
								<select class="select2 select2-hidden-accessible" id="tx_establecimiento" name="tx_establecimiento" data-placeholder="Seleccione establecimiento" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" required>
									<option value=""></option>
									@foreach ($establecimientos as $establecimiento)
										<option value={{$establecimiento->id}} {{isset($user->establecimiento) && $user->establecimiento->id == $establecimiento->id ? "selected" : ""}}>{{$establecimiento->tx_nombre_minuscula}}</option>
									@endforeach
								</select>					
							</div>
							<div class="col-sm-3">
								<label for="tx_tipo_profesional">Tipo Profesional:<span style="color:#FF0000";>*</span></label>
								<select class="select2 select2-hidden-accessible" id="tx_tipo_profesional" name="tx_tipo_profesional" data-placeholder="Seleccione tipo profesional" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" required>
									<option value=""></option>
									<option value="STAFF" {{isset($user->tx_tipo_profesional) && $user->tx_tipo_profesional == 'STAFF' ? "selected" : ""}}>Staff</option>
									<option value="BECADO" {{isset($user->tx_tipo_profesional) && $user->tx_tipo_profesional == 'BECADO' ? "selected" : ""}}>Becado</option>
								</select>					
							</div>
							<div class="col-sm-3">
								<label for="group_id">Grupo:<span style="color:#FF0000";>*</span></label>
								<select class="select2 select2-hidden-accessible" id="group_id" name="group_id" data-placeholder="Seleccione grupo" style="width: 100%;" data-select2-id="7" tabindex="-1" aria-hidden="true" required>
									<option value=""></option>
									@foreach ($grupos as $grupo)
										<option value={{$grupo->group_id}} {{isset($user->grupo) && $user->grupo->group_id == $grupo->group_id ? "selected" : ""}}>{{$grupo->description}}</option>
									@endforeach
								</select>					
							</div>
						</div>
					</div>
				@endif
			</div>
		  	<div class="card-footer text-right">
				<button type="submit" class="btn btn-success">Guardar</button>
		  	</div>
		</form>
	  </div>
@stop

@section('js')
<script>
	function getPerson(tx_rut){
		@if (!isset($user))
			$.getJSON("{{action('GetController@getDatosRut')}}?rut="+tx_rut,
			function(data){
				if(data.user && data.encontrado){
					var opcion = confirm("Este Usuario ya existe desea editarlo?");
					if (opcion == true) {
						location.href = data.id+"/edit";
					} else {
						$("#login").val("");
					}
				}
				else{
					if(data.encontrado == true){
						$("#login").val(data.tx_rut);
						$("#name").val(data.tx_nombre);
						$("#name").css('display','').attr('readonly', true);
					}else{
						alert("Rut no encontrado");
						$("#login").val("");
						$("#name").val("");
						$("#name").css('display','').attr('readonly', false);
					}
				}
			})
		@endif
	};

	$('.select2').select2();
</script>
@stop